### ISSUE TITLE
error loading on wsl

### ISSUE THREAD

**Issue by neo451** [Freed-Wu/rime.nvim#2]
目前没有成功在wsl上 load 这个插件，一直得到以下错误：

`
"test.lua" LuaJIT ASSERT lj_api.c:51: index2adr: calling frame is not a C function
`

我还尝试了单独 load rime 的 lua binding，错误是一样的：

```lua
local rime = require "rime"

rime.init {
   shared_data_dir = "/usr/share/rime-data",
   user_data_dir = "~/.local/share/rime-ls",
   log_dir = vim.fs.joinpath(vim.fn.stdpath "data", "rime"),
   distribution_name = "Rime",
   distribution_code_name = "nvim-rime",
   distribution_version = "0.0.1",
   app_name = "rime.nvim-rime",
   min_log_level = 3,
}

```

**Comment by Freed-Wu** [comment]
The error comes from `require'rime'`, right?

**Comment by noearc** [comment]
yes, I just use the neovim embedded luajit, to be exact, it throws the same that the plugins throws, and just quits neovim for me

**Comment by Freed-Wu** [comment]
What is your environment?

**Comment by Freed-Wu** [comment]
Have you tried 0.0.1-1? https://luarocks.org/modules/Freed-Wu/rime.nvim

**Comment by noearc** [comment]
yes I did, but still the same problem, I tried on nvim-0.11 on wsl and nvim-0.10 on arch, both not working, librime is the newest version as well.

**Comment by Freed-Wu** [comment]
Weird. For me:

- OS: ArchLinux rolling
- neovim: 0.10.1
- librime 1.11.1

Can you try

```
paru -S luajit-symlinks
```

In Archlinux?

**Comment by Freed-Wu** [comment]
And, something should be noticed:

1. https://github.com/hchunhui/librime-lua also use lua. If you use this rime plugin, make sure its lua version is same as rime.nvim's lua version (rime.nvim's lua version is neovim's luajit). Otherwise some different lua version's function will conflict.
2. Other rime plugins seems to have undetermined problem. I just disable them and haven't found the reason.
3. luajit-symlinks use luajit as lua5.1. That means `luarocks --lua-verson 5.1` in fact use luajit. I believe it should be helpful.

**Comment by Freed-Wu** [comment]
BTW, Does WSL mean WSL1 or WSL2?

**Comment by Freed-Wu** [comment]
NixOS's librime now updated to 1.12.0, and some API changed https://github.com/rime/librime/pull/877

**Comment by Freed-Wu** [comment]
Now it can work for my NixOS. This is my [configuration.nix](https://github.com/Freed-Wu/Freed-Wu/blob/dev/.local/share/gentoo/etc/nixos/configuration.nix).

WSL2 is a VM based on hyperV. I think it should be same as normal Linux.
